CREATE TABLE LABORATORIO (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PAIS VARCHAR(100) NOT NULL,
    FECHA_FUNDACION DATE,
    AUTOR_EXAMEN VARCHAR(100) NOT NULL
);


CREATE TABLE MUESTRAS_ADN (
    ID SERIAL PRIMARY KEY,
    CODIGO VARCHAR(50),
    TIPO VARCHAR(100),
    FECHA_EXTRACCION DATE,
    FK_LABORATORIO_ID INT NOT NULL,
    AUTOR_EXAMEN VARCHAR(150) NOT NULL,
    CONSTRAINT FK_LABORATORIO_MUESTRAS FOREIGN KEY (FK_LABORATORIO_ID) REFERENCES LABORATORIO(ID)
);


CREATE TABLE ANALISIS (
    ID SERIAL PRIMARY KEY,
    MUTACION_DETECTADA VARCHAR(50),
    PORCENTAJE_COINCIDENCIA VARCHAR(50),
    OBSERVACIONES VARCHAR(150),
    FK_MUESTRASADN_ID INT NOT NULL,
    AUTOR_EXAMEN VARCHAR(150) NOT NULL,
    CONSTRAINT FK_MUESTRAS_ANALISIS FOREIGN KEY (FK_MUESTRASADN_ID) REFERENCES MUESTRAS_ADN(ID),
    CONSTRAINT UNIQUE_FK_MUESTRAS UNIQUE (FK_MUESTRASADN_ID)
);
