
SELECT * FROM MUESTRAS_ADN WHERE ID = 1;
SELECT * FROM MUESTRAS_ADN; 
SELECT * FROM MUESTRAS_ADN WHERE FK_LABORATORIO_ID = 1;
SELECT m.ID AS muestra_id,
       m.CODIGO, m.TIPO, m.FECHA_EXTRACCION, l.ID AS lab_id, l.NOMBRE AS lab_nombre, l.PAIS,
       a.ID  AS analisis_id, a.MUTACION_DETECTADA, a.PORCENTAJE_COINCIDENCIA, a.OBSERVACIONES
FROM MUESTRAS_ADN m
INNER JOIN LABORATORIO l
    ON m.FK_LABORATORIO_ID = l.ID
INNER JOIN ANALISIS a
    ON m.ID = a.FK_MUESTRAS_ADN_ID;
